// This file is automatically generated. Do not edit it directly.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Add your tables here
      // eslint-disable-next-line @typescript-eslint/ban-types
    } & {}
    Views: {
      // Add your views here
      // eslint-disable-next-line @typescript-eslint/ban-types
    } & {}
    Functions: {
      // Add your functions here
      // eslint-disable-next-line @typescript-eslint/ban-types
    } & {}
    Enums: {
      // Add your enums here
      // eslint-disable-next-line @typescript-eslint/ban-types
    } & {}
  }
}
